title: Taller de Base de datos INF-272
description: Repositorio de la materia INF-272
remote_theme: "jekyll/minima@1e8a445"
markdown: kramdown
minima:
  skin: auto
  nav_pages: []
  author:
    name: Roy Ayala Ruiz
  social_links:
    - title: Grupo de Telegram
      icon: telegram
      url: "https://t.me/+gnFWDJY6ULUzMWJh"
    - title: Repositorio github
      icon: github
      url: "https://github.com/Troy8203/Repositorio-272"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

share-links-active:
  twitter: fals
  facebook: fals
  linkedin: fals
  vk: false
  reddit: false

defaults:
  - scope:
      path: ""
      type: "page"
    values:
      layout: "page"
